# Generated by Django 2.1.7 on 2019-04-04 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('backend', '0002_delete_todo'),
    ]

    operations = [
        migrations.CreateModel(
            name='WashingMachineBookings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('washing_machine', models.IntegerField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('used', models.BooleanField(default=False)),
            ],
        ),
    ]
