# Generated by Django 2.1.7 on 2019-04-28 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='washingmachinebookings',
            name='user',
        ),
    ]
